-- ========================================================
-- Petron POS System - phpMyAdmin Designer Layout & Relations Backup
-- Database: petron_pos_db_secure
-- Generated: 2026-10-08 07:06:41
-- ========================================================

CREATE DATABASE IF NOT EXISTS `phpmyadmin` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `phpmyadmin`;

-- 1. Ensure Page Entry Exists in pma__pdf_pages
INSERT INTO `pma__pdf_pages` (`db_name`, `page_nr`, `page_descr`)
VALUES ('petron_pos_db_secure', 1, 'Petron POS Database Schema')
ON DUPLICATE KEY UPDATE `page_descr` = VALUES(`page_descr`);

-- 2. Clear old coordinates for petron_pos_db_secure
DELETE FROM `pma__table_coords` WHERE `db_name` = 'petron_pos_db_secure';

-- 3. Insert Structured Non-Overlapping Coordinates
INSERT INTO `pma__table_coords` (`db_name`, `table_name`, `pdf_page_number`, `x`, `y`) VALUES
('petron_pos_db_secure', 'stations', 0, 50, 50),
('petron_pos_db_secure', 'users', 0, 50, 561),
('petron_pos_db_secure', 'labor_sessions', 0, 50, 1116),
('petron_pos_db_secure', 'password_reset_tokens', 0, 490, 50),
('petron_pos_db_secure', 'login_attempts', 0, 490, 385),
('petron_pos_db_secure', 'user_preferences', 0, 490, 698),
('petron_pos_db_secure', 'user_form_drafts', 0, 490, 945),
('petron_pos_db_secure', 'employee_documents', 0, 490, 1258),
('petron_pos_db_secure', 'fuel_types', 0, 1050, 50),
('petron_pos_db_secure', 'fuel_inventory', 0, 1050, 275),
('petron_pos_db_secure', 'fuel_pricing', 0, 1050, 786),
('petron_pos_db_secure', 'fuel_price_history', 0, 1050, 1099),
('petron_pos_db_secure', 'fuel_variance_reports', 0, 1050, 1544),
('petron_pos_db_secure', 'fuel_pumps', 0, 1490, 50),
('petron_pos_db_secure', 'nozzles', 0, 1490, 495),
('petron_pos_db_secure', 'fuel_calibration_records', 0, 1490, 896),
('petron_pos_db_secure', 'fuel_management_config', 0, 1490, 1297),
('petron_pos_db_secure', 'fuel_config_history', 0, 1490, 1610),
('petron_pos_db_secure', 'fuel_status_history', 0, 1490, 1945),
('petron_pos_db_secure', 'deliveries_oversight', 0, 2050, 50),
('petron_pos_db_secure', 'fuel_batches', 0, 2050, 1133),
('petron_pos_db_secure', 'fuel_stock_in', 0, 2050, 1600),
('petron_pos_db_secure', 'fuel_deliveries', 0, 2050, 2089),
('petron_pos_db_secure', 'fuel_purchase_orders', 0, 2490, 50),
('petron_pos_db_secure', 'fuel_stock_requests', 0, 2490, 627),
('petron_pos_db_secure', 'fuel_stock_request_audit', 0, 2490, 1138),
('petron_pos_db_secure', 'fuel_adjustments', 0, 2490, 1451),
('petron_pos_db_secure', 'fuel_suppliers', 0, 2490, 2028),
('petron_pos_db_secure', 'categories', 0, 3050, 50),
('petron_pos_db_secure', 'product_categories', 0, 3050, 275),
('petron_pos_db_secure', 'product_types', 0, 3050, 478),
('petron_pos_db_secure', 'products', 0, 3050, 659),
('petron_pos_db_secure', 'suppliers', 0, 3050, 1258),
('petron_pos_db_secure', 'station_inventory', 0, 3050, 1593),
('petron_pos_db_secure', 'merchandise_batches', 0, 3490, 50),
('petron_pos_db_secure', 'merchandise_stock_in', 0, 3490, 561),
('petron_pos_db_secure', 'purchase_orders', 0, 3490, 1160),
('petron_pos_db_secure', 'purchase_order_items', 0, 3490, 2111),
('petron_pos_db_secure', 'stock_requests', 0, 3490, 2490),
('petron_pos_db_secure', 'stock_request_audit', 0, 3490, 3023),
('petron_pos_db_secure', 'merchandise_adjustments', 0, 3490, 3358),
('petron_pos_db_secure', 'inventory_products', 0, 3490, 3891),
('petron_pos_db_secure', 'inventory_logs', 0, 3490, 4512),
('petron_pos_db_secure', 'product_config_history', 0, 3490, 4957),
('petron_pos_db_secure', 'product_price_history', 0, 3490, 5270),
('petron_pos_db_secure', 'product_status_history', 0, 3490, 5627),
('petron_pos_db_secure', 'shifts', 0, 4050, 50),
('petron_pos_db_secure', 'shift_periods', 0, 4050, 363),
('petron_pos_db_secure', 'payment_methods', 0, 4050, 698),
('petron_pos_db_secure', 'customers', 0, 4050, 901);

INSERT INTO `pma__table_coords` (`db_name`, `table_name`, `pdf_page_number`, `x`, `y`) VALUES
('petron_pos_db_secure', 'customer_vehicles', 0, 4050, 2292),
('petron_pos_db_secure', 'customer_timeline', 0, 4050, 2671),
('petron_pos_db_secure', 'customer_requests', 0, 4050, 2918),
('petron_pos_db_secure', 'fuel_transactions', 0, 4490, 50),
('petron_pos_db_secure', 'merchandise_transactions', 0, 4490, 869),
('petron_pos_db_secure', 'merchandise_transaction_items', 0, 4490, 2678),
('petron_pos_db_secure', 'merchandise_transaction_audit', 0, 4490, 3057),
('petron_pos_db_secure', 'fuel_sales_closing', 0, 4490, 3348),
('petron_pos_db_secure', 'mechanics', 0, 4930, 50),
('petron_pos_db_secure', 'job_orders', 0, 4930, 517),
('petron_pos_db_secure', 'job_order_parts', 0, 4930, 2150),
('petron_pos_db_secure', 'job_order_service_types', 0, 4930, 2419),
('petron_pos_db_secure', 'service_categories', 0, 4930, 3172),
('petron_pos_db_secure', 'service_rates', 0, 4930, 3463),
('petron_pos_db_secure', 'service_fee_history', 0, 4930, 3798),
('petron_pos_db_secure', 'pending_price_approvals', 0, 4930, 4221),
('petron_pos_db_secure', 'service_parts_mapping', 0, 4930, 4886),
('petron_pos_db_secure', 'vehicle_types', 0, 4930, 5221),
('petron_pos_db_secure', 'vehicle_inspection_items', 0, 4930, 5600),
('petron_pos_db_secure', 'customer_accounts_receivable', 0, 5490, 50),
('petron_pos_db_secure', 'customer_credit_transactions', 0, 5490, 407),
('petron_pos_db_secure', 'transaction_adjustments', 0, 5490, 676),
('petron_pos_db_secure', 'transaction_requests', 0, 5490, 1077),
('petron_pos_db_secure', 'voided_transactions', 0, 5490, 1566),
('petron_pos_db_secure', 'adjustment_history', 0, 5490, 2033),
('petron_pos_db_secure', 'adjustment_types', 0, 5490, 2390),
('petron_pos_db_secure', 'loyalty_programs', 0, 5930, 50),
('petron_pos_db_secure', 'loyalty_accounts', 0, 5930, 341),
('petron_pos_db_secure', 'loyalty_transactions', 0, 5930, 654),
('petron_pos_db_secure', 'audit_logs', 0, 6490, 50),
('petron_pos_db_secure', 'audit_trail', 0, 6490, 473),
('petron_pos_db_secure', 'activity_logs', 0, 6490, 1072),
('petron_pos_db_secure', 'error_tracking_logs', 0, 6490, 1363),
('petron_pos_db_secure', 'payment_audit_log', 0, 6490, 1676),
('petron_pos_db_secure', 'sys_health_report_log', 0, 6490, 2033),
('petron_pos_db_secure', 'database_backups', 0, 6490, 2412),
('petron_pos_db_secure', 'restore_logs', 0, 6490, 2835),
('petron_pos_db_secure', 'system_settings', 0, 6930, 50),
('petron_pos_db_secure', 'system_settings_audit', 0, 6930, 385),
('petron_pos_db_secure', 'system_config', 0, 6930, 654),
('petron_pos_db_secure', 'module_config', 0, 6930, 923),
('petron_pos_db_secure', 'module_config_audit', 0, 6930, 1258),
('petron_pos_db_secure', 'module_settings', 0, 6930, 1615),
('petron_pos_db_secure', 'module_station_config', 0, 6930, 1994),
('petron_pos_db_secure', 'receipt_config', 0, 6930, 2241),
('petron_pos_db_secure', 'receipt_corrections', 0, 6930, 2884),
('petron_pos_db_secure', 'notifications', 0, 7370, 50),
('petron_pos_db_secure', 'staff_calendar_events', 0, 7370, 517),
('petron_pos_db_secure', 'staff_event_types', 0, 7370, 940),
('petron_pos_db_secure', 'staff_color_config', 0, 7370, 1319);

INSERT INTO `pma__table_coords` (`db_name`, `table_name`, `pdf_page_number`, `x`, `y`) VALUES
('petron_pos_db_secure', 'manager_color_config', 0, 7370, 1588),
('petron_pos_db_secure', 'master_data_requests', 0, 7370, 1857),
('petron_pos_db_secure', 'admin_compliance_deadlines', 0, 7370, 2236),
('petron_pos_db_secure', 'ph_regions', 0, 7370, 2593),
('petron_pos_db_secure', 'ui_config', 0, 7370, 2774),
('petron_pos_db_secure', 'integration_audit', 0, 7370, 3065),
('petron_pos_db_secure', 'variance_alerts', 0, 7370, 3334);

INSERT INTO `pma__table_coords` (`db_name`, `table_name`, `pdf_page_number`, `x`, `y`) VALUES
('petron_pos_db_secure', 'stations', 1, 50, 50),
('petron_pos_db_secure', 'users', 1, 50, 561),
('petron_pos_db_secure', 'labor_sessions', 1, 50, 1116),
('petron_pos_db_secure', 'password_reset_tokens', 1, 490, 50),
('petron_pos_db_secure', 'login_attempts', 1, 490, 385),
('petron_pos_db_secure', 'user_preferences', 1, 490, 698),
('petron_pos_db_secure', 'user_form_drafts', 1, 490, 945),
('petron_pos_db_secure', 'employee_documents', 1, 490, 1258),
('petron_pos_db_secure', 'fuel_types', 1, 1050, 50),
('petron_pos_db_secure', 'fuel_inventory', 1, 1050, 275),
('petron_pos_db_secure', 'fuel_pricing', 1, 1050, 786),
('petron_pos_db_secure', 'fuel_price_history', 1, 1050, 1099),
('petron_pos_db_secure', 'fuel_variance_reports', 1, 1050, 1544),
('petron_pos_db_secure', 'fuel_pumps', 1, 1490, 50),
('petron_pos_db_secure', 'nozzles', 1, 1490, 495),
('petron_pos_db_secure', 'fuel_calibration_records', 1, 1490, 896),
('petron_pos_db_secure', 'fuel_management_config', 1, 1490, 1297),
('petron_pos_db_secure', 'fuel_config_history', 1, 1490, 1610),
('petron_pos_db_secure', 'fuel_status_history', 1, 1490, 1945),
('petron_pos_db_secure', 'deliveries_oversight', 1, 2050, 50),
('petron_pos_db_secure', 'fuel_batches', 1, 2050, 1133),
('petron_pos_db_secure', 'fuel_stock_in', 1, 2050, 1600),
('petron_pos_db_secure', 'fuel_deliveries', 1, 2050, 2089),
('petron_pos_db_secure', 'fuel_purchase_orders', 1, 2490, 50),
('petron_pos_db_secure', 'fuel_stock_requests', 1, 2490, 627),
('petron_pos_db_secure', 'fuel_stock_request_audit', 1, 2490, 1138),
('petron_pos_db_secure', 'fuel_adjustments', 1, 2490, 1451),
('petron_pos_db_secure', 'fuel_suppliers', 1, 2490, 2028),
('petron_pos_db_secure', 'categories', 1, 3050, 50),
('petron_pos_db_secure', 'product_categories', 1, 3050, 275),
('petron_pos_db_secure', 'product_types', 1, 3050, 478),
('petron_pos_db_secure', 'products', 1, 3050, 659),
('petron_pos_db_secure', 'suppliers', 1, 3050, 1258),
('petron_pos_db_secure', 'station_inventory', 1, 3050, 1593),
('petron_pos_db_secure', 'merchandise_batches', 1, 3490, 50),
('petron_pos_db_secure', 'merchandise_stock_in', 1, 3490, 561),
('petron_pos_db_secure', 'purchase_orders', 1, 3490, 1160),
('petron_pos_db_secure', 'purchase_order_items', 1, 3490, 2111),
('petron_pos_db_secure', 'stock_requests', 1, 3490, 2490),
('petron_pos_db_secure', 'stock_request_audit', 1, 3490, 3023),
('petron_pos_db_secure', 'merchandise_adjustments', 1, 3490, 3358),
('petron_pos_db_secure', 'inventory_products', 1, 3490, 3891),
('petron_pos_db_secure', 'inventory_logs', 1, 3490, 4512),
('petron_pos_db_secure', 'product_config_history', 1, 3490, 4957),
('petron_pos_db_secure', 'product_price_history', 1, 3490, 5270),
('petron_pos_db_secure', 'product_status_history', 1, 3490, 5627),
('petron_pos_db_secure', 'shifts', 1, 4050, 50),
('petron_pos_db_secure', 'shift_periods', 1, 4050, 363),
('petron_pos_db_secure', 'payment_methods', 1, 4050, 698),
('petron_pos_db_secure', 'customers', 1, 4050, 901);

INSERT INTO `pma__table_coords` (`db_name`, `table_name`, `pdf_page_number`, `x`, `y`) VALUES
('petron_pos_db_secure', 'customer_vehicles', 1, 4050, 2292),
('petron_pos_db_secure', 'customer_timeline', 1, 4050, 2671),
('petron_pos_db_secure', 'customer_requests', 1, 4050, 2918),
('petron_pos_db_secure', 'fuel_transactions', 1, 4490, 50),
('petron_pos_db_secure', 'merchandise_transactions', 1, 4490, 869),
('petron_pos_db_secure', 'merchandise_transaction_items', 1, 4490, 2678),
('petron_pos_db_secure', 'merchandise_transaction_audit', 1, 4490, 3057),
('petron_pos_db_secure', 'fuel_sales_closing', 1, 4490, 3348),
('petron_pos_db_secure', 'mechanics', 1, 4930, 50),
('petron_pos_db_secure', 'job_orders', 1, 4930, 517),
('petron_pos_db_secure', 'job_order_parts', 1, 4930, 2150),
('petron_pos_db_secure', 'job_order_service_types', 1, 4930, 2419),
('petron_pos_db_secure', 'service_categories', 1, 4930, 3172),
('petron_pos_db_secure', 'service_rates', 1, 4930, 3463),
('petron_pos_db_secure', 'service_fee_history', 1, 4930, 3798),
('petron_pos_db_secure', 'pending_price_approvals', 1, 4930, 4221),
('petron_pos_db_secure', 'service_parts_mapping', 1, 4930, 4886),
('petron_pos_db_secure', 'vehicle_types', 1, 4930, 5221),
('petron_pos_db_secure', 'vehicle_inspection_items', 1, 4930, 5600),
('petron_pos_db_secure', 'customer_accounts_receivable', 1, 5490, 50),
('petron_pos_db_secure', 'customer_credit_transactions', 1, 5490, 407),
('petron_pos_db_secure', 'transaction_adjustments', 1, 5490, 676),
('petron_pos_db_secure', 'transaction_requests', 1, 5490, 1077),
('petron_pos_db_secure', 'voided_transactions', 1, 5490, 1566),
('petron_pos_db_secure', 'adjustment_history', 1, 5490, 2033),
('petron_pos_db_secure', 'adjustment_types', 1, 5490, 2390),
('petron_pos_db_secure', 'loyalty_programs', 1, 5930, 50),
('petron_pos_db_secure', 'loyalty_accounts', 1, 5930, 341),
('petron_pos_db_secure', 'loyalty_transactions', 1, 5930, 654),
('petron_pos_db_secure', 'audit_logs', 1, 6490, 50),
('petron_pos_db_secure', 'audit_trail', 1, 6490, 473),
('petron_pos_db_secure', 'activity_logs', 1, 6490, 1072),
('petron_pos_db_secure', 'error_tracking_logs', 1, 6490, 1363),
('petron_pos_db_secure', 'payment_audit_log', 1, 6490, 1676),
('petron_pos_db_secure', 'sys_health_report_log', 1, 6490, 2033),
('petron_pos_db_secure', 'database_backups', 1, 6490, 2412),
('petron_pos_db_secure', 'restore_logs', 1, 6490, 2835),
('petron_pos_db_secure', 'system_settings', 1, 6930, 50),
('petron_pos_db_secure', 'system_settings_audit', 1, 6930, 385),
('petron_pos_db_secure', 'system_config', 1, 6930, 654),
('petron_pos_db_secure', 'module_config', 1, 6930, 923),
('petron_pos_db_secure', 'module_config_audit', 1, 6930, 1258),
('petron_pos_db_secure', 'module_settings', 1, 6930, 1615),
('petron_pos_db_secure', 'module_station_config', 1, 6930, 1994),
('petron_pos_db_secure', 'receipt_config', 1, 6930, 2241),
('petron_pos_db_secure', 'receipt_corrections', 1, 6930, 2884),
('petron_pos_db_secure', 'notifications', 1, 7370, 50),
('petron_pos_db_secure', 'staff_calendar_events', 1, 7370, 517),
('petron_pos_db_secure', 'staff_event_types', 1, 7370, 940),
('petron_pos_db_secure', 'staff_color_config', 1, 7370, 1319);

INSERT INTO `pma__table_coords` (`db_name`, `table_name`, `pdf_page_number`, `x`, `y`) VALUES
('petron_pos_db_secure', 'manager_color_config', 1, 7370, 1588),
('petron_pos_db_secure', 'master_data_requests', 1, 7370, 1857),
('petron_pos_db_secure', 'admin_compliance_deadlines', 1, 7370, 2236),
('petron_pos_db_secure', 'ph_regions', 1, 7370, 2593),
('petron_pos_db_secure', 'ui_config', 1, 7370, 2774),
('petron_pos_db_secure', 'integration_audit', 1, 7370, 3065),
('petron_pos_db_secure', 'variance_alerts', 1, 7370, 3334);

-- 4. Sync phpMyAdmin Designer Relations
INSERT INTO `pma__relation` (`master_db`, `master_table`, `master_field`, `foreign_db`, `foreign_table`, `foreign_field`) VALUES
('petron_pos_db_secure', 'activity_logs', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'adjustment_history', 'adjustment_type_id', 'petron_pos_db_secure', 'adjustment_types', 'id'),
('petron_pos_db_secure', 'adjustment_history', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'adjustment_history', 'request_id', 'petron_pos_db_secure', 'stock_requests', 'id'),
('petron_pos_db_secure', 'adjustment_history', 'requested_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'adjustment_history', 'transaction_db_id', 'petron_pos_db_secure', 'fuel_transactions', 'id'),
('petron_pos_db_secure', 'admin_compliance_deadlines', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'admin_compliance_deadlines', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'audit_logs', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'audit_trail', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'audit_trail', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'audit_trail', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'customer_accounts_receivable', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'customer_accounts_receivable', 'transaction_db_id', 'petron_pos_db_secure', 'merchandise_transactions', 'id'),
('petron_pos_db_secure', 'customer_credit_transactions', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'customer_credit_transactions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'customer_requests', 'customer_record_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'customer_requests', 'requested_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'customer_requests', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'customer_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'customer_timeline', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'customer_timeline', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'customer_vehicles', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'customers', 'mgr_reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'customers', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'customers', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'database_backups', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'database_backups', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'deliveries_oversight', 'admin_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'deliveries_oversight', 'batch_id', 'petron_pos_db_secure', 'fuel_batches', 'id'),
('petron_pos_db_secure', 'deliveries_oversight', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'deliveries_oversight', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'deliveries_oversight', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'employee_documents', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'error_tracking_logs', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_adjustments', 'adjustment_type_id', 'petron_pos_db_secure', 'adjustment_types', 'id'),
('petron_pos_db_secure', 'fuel_adjustments', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_adjustments', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'fuel_adjustments', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_adjustments', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_batches', 'delivery_id', 'petron_pos_db_secure', 'deliveries_oversight', 'id'),
('petron_pos_db_secure', 'fuel_batches', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_batches', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'fuel_batches', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_calibration_records', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_calibration_records', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_config_history', 'fuel_inventory_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
('petron_pos_db_secure', 'fuel_config_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_config_history', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_deliveries', 'received_by', 'petron_pos_db_secure', 'users', 'id')
ON DUPLICATE KEY UPDATE foreign_db=VALUES(foreign_db), foreign_table=VALUES(foreign_table), foreign_field=VALUES(foreign_field);

INSERT INTO `pma__relation` (`master_db`, `master_table`, `master_field`, `foreign_db`, `foreign_table`, `foreign_field`) VALUES
('petron_pos_db_secure', 'fuel_deliveries', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_deliveries', 'verified_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_inventory', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'fuel_inventory', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_inventory', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_management_config', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_management_config', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_price_history', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_price_history', 'fuel_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
('petron_pos_db_secure', 'fuel_price_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_price_history', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_pricing', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_pricing', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'fuel_pricing', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_pumps', 'calibration_updated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_pumps', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'fuel_pumps', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_pumps', 'tank_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
('petron_pos_db_secure', 'fuel_purchase_orders', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_purchase_orders', 'batch_id', 'petron_pos_db_secure', 'fuel_batches', 'id'),
('petron_pos_db_secure', 'fuel_purchase_orders', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_purchase_orders', 'delivered_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_purchase_orders', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'fuel_purchase_orders', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_purchase_orders', 'supplier_id', 'petron_pos_db_secure', 'suppliers', 'id'),
('petron_pos_db_secure', 'fuel_sales_closing', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_sales_closing', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_status_history', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_status_history', 'fuel_inventory_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
('petron_pos_db_secure', 'fuel_status_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_stock_in', 'delivery_id', 'petron_pos_db_secure', 'deliveries_oversight', 'id'),
('petron_pos_db_secure', 'fuel_stock_in', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_stock_in', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_stock_request_audit', 'performed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_stock_request_audit', 'request_id', 'petron_pos_db_secure', 'fuel_stock_requests', 'id'),
('petron_pos_db_secure', 'fuel_stock_requests', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'fuel_stock_requests', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_stock_requests', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_stock_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_suppliers', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_transactions', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'fuel_transactions', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_transactions', 'pump_id', 'petron_pos_db_secure', 'fuel_pumps', 'id'),
('petron_pos_db_secure', 'fuel_transactions', 'shift_id', 'petron_pos_db_secure', 'shifts', 'id'),
('petron_pos_db_secure', 'fuel_transactions', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_transactions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'fuel_transactions', 'validated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'fuel_types', 'category_id', 'petron_pos_db_secure', 'categories', 'id'),
('petron_pos_db_secure', 'fuel_variance_reports', 'pump_id', 'petron_pos_db_secure', 'fuel_pumps', 'id'),
('petron_pos_db_secure', 'fuel_variance_reports', 'station_id', 'petron_pos_db_secure', 'stations', 'id')
ON DUPLICATE KEY UPDATE foreign_db=VALUES(foreign_db), foreign_table=VALUES(foreign_table), foreign_field=VALUES(foreign_field);

INSERT INTO `pma__relation` (`master_db`, `master_table`, `master_field`, `foreign_db`, `foreign_table`, `foreign_field`) VALUES
('petron_pos_db_secure', 'fuel_variance_reports', 'tank_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
('petron_pos_db_secure', 'integration_audit', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'inventory_logs', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
('petron_pos_db_secure', 'inventory_logs', 'reference_id', 'petron_pos_db_secure', 'purchase_orders', 'id'),
('petron_pos_db_secure', 'inventory_logs', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'inventory_logs', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'inventory_products', 'category_id', 'petron_pos_db_secure', 'categories', 'id'),
('petron_pos_db_secure', 'inventory_products', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'job_order_parts', 'job_order_id', 'petron_pos_db_secure', 'job_orders', 'id'),
('petron_pos_db_secure', 'job_order_parts', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
('petron_pos_db_secure', 'job_order_service_types', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'job_order_service_types', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'job_order_service_types', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'job_order_service_types', 'submitted_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'job_orders', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'job_orders', 'assigned_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'job_orders', 'assigned_mechanic_id', 'petron_pos_db_secure', 'mechanics', 'id'),
('petron_pos_db_secure', 'job_orders', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'job_orders', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'job_orders', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'job_orders', 'service_category_id', 'petron_pos_db_secure', 'service_categories', 'id'),
('petron_pos_db_secure', 'job_orders', 'shift_id', 'petron_pos_db_secure', 'shifts', 'id'),
('petron_pos_db_secure', 'job_orders', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'job_orders', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'job_orders', 'validated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'labor_sessions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'labor_sessions', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'login_attempts', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'loyalty_accounts', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'loyalty_accounts', 'program_id', 'petron_pos_db_secure', 'loyalty_programs', 'id'),
('petron_pos_db_secure', 'loyalty_transactions', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'loyalty_transactions', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'loyalty_transactions', 'loyalty_account_id', 'petron_pos_db_secure', 'loyalty_accounts', 'id'),
('petron_pos_db_secure', 'manager_color_config', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'master_data_requests', 'requested_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'master_data_requests', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'master_data_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'mechanics', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'merchandise_adjustments', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'merchandise_adjustments', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
('petron_pos_db_secure', 'merchandise_adjustments', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'merchandise_batches', 'delivery_id', 'petron_pos_db_secure', 'deliveries_oversight', 'id'),
('petron_pos_db_secure', 'merchandise_batches', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'merchandise_batches', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
('petron_pos_db_secure', 'merchandise_batches', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'merchandise_batches', 'validated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'merchandise_stock_in', 'delivery_id', 'petron_pos_db_secure', 'deliveries_oversight', 'id'),
('petron_pos_db_secure', 'merchandise_stock_in', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'merchandise_stock_in', 'po_id', 'petron_pos_db_secure', 'purchase_orders', 'id'),
('petron_pos_db_secure', 'merchandise_stock_in', 'product_id', 'petron_pos_db_secure', 'products', 'id')
ON DUPLICATE KEY UPDATE foreign_db=VALUES(foreign_db), foreign_table=VALUES(foreign_table), foreign_field=VALUES(foreign_field);

INSERT INTO `pma__relation` (`master_db`, `master_table`, `master_field`, `foreign_db`, `foreign_table`, `foreign_field`) VALUES
('petron_pos_db_secure', 'merchandise_stock_in', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'merchandise_transaction_audit', 'transaction_id', 'petron_pos_db_secure', 'merchandise_transactions', 'id'),
('petron_pos_db_secure', 'merchandise_transaction_audit', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'merchandise_transaction_items', 'batch_id', 'petron_pos_db_secure', 'merchandise_batches', 'id'),
('petron_pos_db_secure', 'merchandise_transaction_items', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
('petron_pos_db_secure', 'merchandise_transaction_items', 'transaction_id', 'petron_pos_db_secure', 'merchandise_transactions', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'credit_customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'job_order_db_id', 'petron_pos_db_secure', 'job_orders', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'job_order_id', 'petron_pos_db_secure', 'job_orders', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'job_order_mechanic_id', 'petron_pos_db_secure', 'mechanics', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'payment_method_id', 'petron_pos_db_secure', 'payment_methods', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'shift_id', 'petron_pos_db_secure', 'shifts', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'merchandise_transactions', 'validated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'module_config', 'module_key', 'petron_pos_db_secure', 'module_settings', 'module_key'),
('petron_pos_db_secure', 'module_config_audit', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'module_station_config', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'module_station_config', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'notifications', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'nozzles', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'nozzles', 'pump_id', 'petron_pos_db_secure', 'fuel_pumps', 'id'),
('petron_pos_db_secure', 'nozzles', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'nozzles', 'tank_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
('petron_pos_db_secure', 'password_reset_tokens', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'payment_audit_log', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'payment_audit_log', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'pending_price_approvals', 'admin_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'pending_price_approvals', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'pending_price_approvals', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'pending_price_approvals', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
('petron_pos_db_secure', 'pending_price_approvals', 'requested_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'pending_price_approvals', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'pending_price_approvals', 'service_type_id', 'petron_pos_db_secure', 'service_types', 'id'),
('petron_pos_db_secure', 'pending_price_approvals', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'product_config_history', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
('petron_pos_db_secure', 'product_config_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'product_price_history', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'product_price_history', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
('petron_pos_db_secure', 'product_price_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'product_status_history', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'product_status_history', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
('petron_pos_db_secure', 'product_status_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'products', 'category_id', 'petron_pos_db_secure', 'product_categories', 'id'),
('petron_pos_db_secure', 'products', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
('petron_pos_db_secure', 'products', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'products', 'top_category_id', 'petron_pos_db_secure', 'categories', 'id'),
('petron_pos_db_secure', 'products', 'type_id', 'petron_pos_db_secure', 'product_types', 'id'),
('petron_pos_db_secure', 'purchase_order_items', 'po_id', 'petron_pos_db_secure', 'purchase_orders', 'id')
ON DUPLICATE KEY UPDATE foreign_db=VALUES(foreign_db), foreign_table=VALUES(foreign_table), foreign_field=VALUES(foreign_field);

INSERT INTO `pma__relation` (`master_db`, `master_table`, `master_field`, `foreign_db`, `foreign_table`, `foreign_field`) VALUES
('petron_pos_db_secure', 'purchase_order_items', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
('petron_pos_db_secure', 'purchase_orders', 'admin_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'purchase_orders', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'purchase_orders', 'batch_id', 'petron_pos_db_secure', 'fuel_batches', 'id'),
('petron_pos_db_secure', 'purchase_orders', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'purchase_orders', 'request_id', 'petron_pos_db_secure', 'stock_requests', 'id'),
('petron_pos_db_secure', 'purchase_orders', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'purchase_orders', 'supplier_id', 'petron_pos_db_secure', 'suppliers', 'id'),
('petron_pos_db_secure', 'receipt_config', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'receipt_config', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'receipt_corrections', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'receipt_corrections', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'restore_logs', 'restored_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'service_fee_history', 'approval_id', 'petron_pos_db_secure', 'pending_price_approvals', 'id'),
('petron_pos_db_secure', 'service_fee_history', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'service_fee_history', 'service_id', 'petron_pos_db_secure', 'service_categories', 'id'),
('petron_pos_db_secure', 'service_parts_mapping', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
('petron_pos_db_secure', 'service_parts_mapping', 'service_category_id', 'petron_pos_db_secure', 'service_categories', 'id'),
('petron_pos_db_secure', 'service_rates', 'service_category_id', 'petron_pos_db_secure', 'service_categories', 'id'),
('petron_pos_db_secure', 'service_rates', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'staff_calendar_events', 'event_type_id', 'petron_pos_db_secure', 'staff_event_types', 'id'),
('petron_pos_db_secure', 'staff_calendar_events', 'manager_assigned_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'staff_calendar_events', 'staff_encoder_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'staff_calendar_events', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'staff_color_config', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'staff_event_types', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'staff_event_types', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'station_inventory', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
('petron_pos_db_secure', 'station_inventory', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'stations', 'region_id', 'petron_pos_db_secure', 'ph_regions', 'id'),
('petron_pos_db_secure', 'stock_request_audit', 'performed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'stock_request_audit', 'request_id', 'petron_pos_db_secure', 'stock_requests', 'id'),
('petron_pos_db_secure', 'stock_request_audit', 'stock_request_id', 'petron_pos_db_secure', 'stock_requests', 'id'),
('petron_pos_db_secure', 'stock_requests', 'item_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
('petron_pos_db_secure', 'stock_requests', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'stock_requests', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'stock_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'suppliers', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'sys_health_report_log', 'recorded_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'sys_health_report_log', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'system_config', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'system_settings', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'system_settings', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'system_settings_audit', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'transaction_adjustments', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'transaction_requests', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'transaction_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'ui_config', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'user_form_drafts', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'user_form_drafts', 'user_id', 'petron_pos_db_secure', 'users', 'id')
ON DUPLICATE KEY UPDATE foreign_db=VALUES(foreign_db), foreign_table=VALUES(foreign_table), foreign_field=VALUES(foreign_field);

INSERT INTO `pma__relation` (`master_db`, `master_table`, `master_field`, `foreign_db`, `foreign_table`, `foreign_field`) VALUES
('petron_pos_db_secure', 'user_preferences', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'users', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'variance_alerts', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'variance_alerts', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'vehicle_inspection_items', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'vehicle_inspection_items', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'vehicle_types', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'vehicle_types', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'vehicle_types', 'submitted_by', 'petron_pos_db_secure', 'users', 'id'),
('petron_pos_db_secure', 'voided_transactions', 'merchandise_txn_id', 'petron_pos_db_secure', 'merchandise_transactions', 'id'),
('petron_pos_db_secure', 'voided_transactions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
('petron_pos_db_secure', 'voided_transactions', 'voided_by', 'petron_pos_db_secure', 'users', 'id')
ON DUPLICATE KEY UPDATE foreign_db=VALUES(foreign_db), foreign_table=VALUES(foreign_table), foreign_field=VALUES(foreign_field);

